SRCS = \
	bask_demod_de.cpp \
	bask_mod_de.cpp \
	bit_src_de.cpp \
	ltf_nd_filter.cpp \
	mixer_de.cpp \
	rectifier.cpp \
	sampler_de.cpp \
	sin_src.cpp

SRCS_EXE = \
	sc_main.cpp

include ../Makefile.defs

